#  Copyright (c) 2012-2019, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito_dsj and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_dsj.


# Settings relevant for the hitobito_dsj wagon
# Overrides settings from the main application
application:
  logo:
    image: logo.svg
    height: 100
    width: 300
  languages:
    de: Deutsch
    fr: Français
    it: Italiano
  correspondence_languages:
    de: Deutsch
    fr: Français
    it: Italiano
    en: English
    rm: Rumantsch



# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-dsj@puzzle.ch
